[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trebuchet = { path = "../lib/trebuchet" }
cube_game = { path = "../lib/cube_game" }
gondola_lift = { path = "../lib/gondola_lift" }
scratchcard = { path = "../lib/scratchcard" }
almanac = { path = "../lib/almanac" }
boat_race = { path = "../lib/boat_race" }
camel_cards = { path = "../lib/camel_cards" }
network_nodes = { path = "../lib/network_nodes" }
oasis = { path = "../lib/oasis" }
pipe_maze = { path = "../lib/pipe_maze" }
observatory = { path = "../lib/observatory" }