[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trebuchet = { path = "../lib/trebuchet" }
cube_game = { path = "../lib/cube_game" }
gondola_lift = { path = "../lib/gondola_lift" }
scratchcard = { path = "../lib/scratchcard" }